language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - /home/travis/.cache/firebase/emulators
before_script:
  - "npm install -g firebase-tools"
  - "cd functions && npm install && cd .."
script:
  #disable using CI env variable
  - "CI=false"
  #remember to use "chmod +x (your_shell_script)" to change permission of your shell script
  - firebase emulators:exec ./integration-test.sh
  #- "npm run test"
  - "npm run build"

after_failure:
  - "cat /home/travis/.npm/_logs/*.log"
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $TripPlanner_Github_Token
  local_dir: build
  on:
    branch: master