enum ActionType{
    SET_ITINERARY = 'SET_ITINERARY',
    SET_ITINERARY_SUCCESSFUL = 'SET_ITINERARY_SUCCESSFUL',
    CLEAR_ALL_SCHEDULE_STATE = 'CLEAR_ALL_SCHEDULE_STATE',
    CLEAR_ALL_SCHEDULE_STATE_SUCCESSFUL = 'CLEAR_ALL_SCHEDULE_STATE_SUCCESSFUL',
  };
  
  export default ActionType;