enum ActionType{
    SET_ITINERARY = 'SET_ITINERARY',
    SET_ITINERARY_SUCCESSFUL = 'SET_ITINERARY_SUCCESSFUL',
    CLEAR_ALL_SCHEDULE_STATE = 'CLEAR_ALL_SCHEDULE_STATE',
    CLEAR_ALL_SCHEDULE_STATE_SUCCESSFUL = 'CLEAR_ALL_SCHEDULE_STATE_SUCCESSFUL',
    CREATE_SCHEDULE = 'CREATE_SCHEDULE',
    LISTEN_ON_SCHEDULES_START = 'LISTEN_ON_SCHEDULES_START',
    LISTEN_ON_SCHEDULES_STOP = 'LISTEN_ON_SCHEDULES_STOP',
  };
  
  export default ActionType;