enum ActionType{
    SET_TRIP_ARCHIVE = 'SET_TRIP_ARCHIVE',
    SET_TRIP_ARCHIVE_SUCCESSFUL = 'SET_TRIP_ARCHIVE_SUCCESSFUL',
    CLEAR_ALL_ITINERARY_STATE = 'CLEAR_ALL_ITINERARY_STATE',
    CLEAR_ALL_ITINERARY_STATE_SUCCESSFUL = 'CLEAR_ALL_ITINERARY_STATE_SUCCESSFUL',
    FETCH_ITINERARIES_START = 'FETCH_ITINERARIES_START',
    FETCH_MORE_ITINERARIES_START = 'FETCH_MORE_ITINERARIES_START',
    CREATE_ITINERARY_START = 'CREATE_ITINERARY_START',
    CREATE_ITINERARY_STATE_RESET = 'CREATE_ITINERARY_STATE_RESET',
    DELETE_ITINERARY_START = 'DELETE_ITINERARY_START',
    DELETE_ITINERARY_STATE_RESET = 'DELETE_ITINERARY_STATE_RESET',
  };
  
  export default ActionType;