enum ActionType{
    SET_TRIP_ARCHIVE = 'SET_TRIP_ARCHIVE',
    SET_TRIP_ARCHIVE_SUCCESSFUL = 'SET_TRIP_ARCHIVE_SUCCESSFUL',
    CLEAR_ALL_ITINERARY_STATE = 'CLEAR_ALL_ITINERARY_STATE',
    CLEAR_ALL_ITINERARY_STATE_SUCCESSFUL = 'CLEAR_ALL_ITINERARY_STATE_SUCCESSFUL',
    FETCH_ITINERARIES_START = 'FETCH_ITINERARIES_START',
    FETCH_ITINERARIES_FAIL = 'FETCH_ITINERARIES_FAIL',
    FETCH_ITINERARIES_SUCCESSFUL = 'FETCH_ITINERARIES_SUCCESSFUL',
  };
  
  export default ActionType;