enum ActionType {
    CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE',
    CHANGE_HEADER_TITLE_SUCCESSFUL = 'CHANGE_HEADER_TITLE_SUCCESSFUL',
    CHANGE_HEADER_TITLE_FAIL = 'CHANGE_HEADER_TITLE_FAIL',
}

export default ActionType;