
enum ActionType{
  FETCH_TRIP_ARCHIVES_START = 'FETCH_TRIP_ARCHIVES_START',
  FETCH_MORE_START = 'FETCH_MORE_START',
  CREATE_TRIP_ARCHIVE_START = 'CREATE_TRIP_ARCHIVE_START',
  CREATE_TRIP_ARCHIVE_STATE_RESET = 'CREATE_TRIP_ARCHIVE_STATE_RESET',
  DELETE_TRIP_ARCHIVE_START = 'DELETE_TRIP_ARCHIVE_START',
  DELETE_TRIP_ARCHIVE_STATE_RESET = 'DELETE_TRIP_ARCHIVE_STATE_RESET',
  UPDATE_TRIP_ARCHIVE_NAME_START = 'UPDATE_TRIP_ARCHIVE_NAME_START',
  UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET = 'UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET',
  CLEAR_TRIP_ARCHIVE_START = 'CLEAR_TRIP_ARCHIVE_START',
};

export default ActionType;

