
enum ActionType{
  FETCH_TRIP_ARCHIVES_START = 'FETCH_TRIP_ARCHIVES_START',
  FETCH_TRIP_ARCHIVES_SUCCESSFUL = 'FETCH_TRIP_ARCHIVES_SUCCESSFUL',
  FETCH_TRIP_ARCHIVES_FAIL = 'FETCH_TRIP_ARCHIVES_FAIL',
  CREATE_TRIP_ARCHIVE_START = 'CREATE_TRIP_ARCHIVE_START',
  CREATE_TRIP_ARCHIVE_SUCCESSFUL = 'CREATE_TRIP_ARCHIVE_SUCCESSFUL',
  CREATE_TRIP_ARCHIVE_FAIL = 'CREATE_TRIP_ARCHIVE_FAIL',
  CREATE_TRIP_ARCHIVE_STATE_RESET = 'CREATE_TRIP_ARCHIVE_STATE_RESET',
  CREATE_TRIP_ARCHIVE_RESET_SUCCESSFUL = 'CREATE_TRIP_ARCHIVE_RESET_SUCCESSFUL',
  DELETE_TRIP_ARCHIVE_START = 'DELETE_TRIP_ARCHIVE_START',
  DELETE_TRIP_ARCHIVE_FAIL = 'DELETE_TRIP_ARCHIVE_FAIL',
  DELETE_TRIP_ARCHIVE_SUCCESSFUL = 'DELETE_TRIP_ARCHIVE_SUCCESSFUL',
  DELETE_TRIP_ARCHIVE_STATE_RESET = 'DELETE_TRIP_ARCHIVE_STATE_RESET',
  DELETE_TRIP_ARCHIVE_RESET_SUCCESSFUL = 'DELETE_TRIP_ARCHIVE_RESET_SUCCESSFUL',
  UPDATE_TRIP_ARCHIVE_NAME_START = 'UPDATE_TRIP_ARCHIVE_NAME_START',
  UPDATE_TRIP_ARCHIVE_NAME_FAIL = 'UPDATE_TRIP_ARCHIVE_NAME_FAIL',
  UPDATE_TRIP_ARCHIVE_NAME_SUCCESSFUL = 'UPDATE_TRIP_ARCHIVE_NAME_SUCCESSFUL',
  UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET = 'UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET',
  UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET_SUCCESSFUL = 'UPDATE_TRIP_ARCHIVE_NAME_STATE_RESET_SUCCESSFUL',
};

export default ActionType;

